modLoader="javafml"
loaderVersion="[33,)"
license="All Rights Reserved unless stated otherwise. Distrubtion permssion is given to FeedTheBeast and CurseForge for use in modpacks"
[[mods]]
    modId="delogger"
    version="${file.jarVersion}"
    authors="UnRealDinnerbone"
    displayName="DeLogger"
    description="Removes Log Spam"